name: flutter_drawing_app
description: A drawing app similar to MS Paint for mobile devices.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  share_plus: ^6.3.4
  uuid: ^3.0.7
  universal_html: ^2.2.4
  shared_preferences: ^2.2.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
