// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9S7CtVpgsjmhQifS4BPmZsA_lugrX-BA',
    appId: '1:254953847733:web:d0602eae64eef60296f7fc',
    messagingSenderId: '254953847733',
    projectId: 'mplkrushikesh-283a2',
    authDomain: 'mplkrushikesh-283a2.firebaseapp.com',
    storageBucket: 'mplkrushikesh-283a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDin2ZWld1GNOTjWWVgi1Q69kv7MUIg2HA',
    appId: '1:254953847733:android:a229333a65f52e5b96f7fc',
    messagingSenderId: '254953847733',
    projectId: 'mplkrushikesh-283a2',
    storageBucket: 'mplkrushikesh-283a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVR9KBluCMt9f8fQtS7RkU6QL_ay_ow6g',
    appId: '1:254953847733:ios:be01e75cbbd6b13096f7fc',
    messagingSenderId: '254953847733',
    projectId: 'mplkrushikesh-283a2',
    storageBucket: 'mplkrushikesh-283a2.firebasestorage.app',
    iosBundleId: 'com.example.mplkrushikesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVR9KBluCMt9f8fQtS7RkU6QL_ay_ow6g',
    appId: '1:254953847733:ios:be01e75cbbd6b13096f7fc',
    messagingSenderId: '254953847733',
    projectId: 'mplkrushikesh-283a2',
    storageBucket: 'mplkrushikesh-283a2.firebasestorage.app',
    iosBundleId: 'com.example.mplkrushikesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9S7CtVpgsjmhQifS4BPmZsA_lugrX-BA',
    appId: '1:254953847733:web:4c08a44eab3b638096f7fc',
    messagingSenderId: '254953847733',
    projectId: 'mplkrushikesh-283a2',
    authDomain: 'mplkrushikesh-283a2.firebaseapp.com',
    storageBucket: 'mplkrushikesh-283a2.firebasestorage.app',
  );
}
