name: Deploy to GitHub Pages

on:
  push:
    branches: [addlogin] # your current branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/mplkrushikesh/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true # This ensures a clean deployment
          commit_message: "Deploy to GitHub Pages"
